# fly.toml app configuration file generated for evacuation-system on 2023-07-12T19:11:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "evacuation-system"
primary_region = "bog"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"